var nodemailer = require('nodemailer');


function sendConfirmation(username, fname, password)
{
	// create reusable transporter object using SMTP transport

	var htmlbody = '!</b><br>Thank you for registering for this website! This is an autogenerated e-mail from soham9015@gmail.com. Replies will not be cared about. This mail also contains your password for the website.<br><br><b>Your password is: ' + password + '</b><br><br>Happy surfing! :)</p>';
	var transporter = nodemailer.createTransport(
	{
	    service: 'Gmail',
	    auth: {
	        user: 'soham9015@gmail.com',
	        pass: 'whatagreatpassword'
	    }
	});

	// NB! No need to recreate the transporter object. You can use
	// the same transporter object for all e-mails

	// setup e-mail data with unicode symbols
	var mailOptions = 
	{
	    from: "CS5610 - Registration <soham9015@gmail.com>", // sender address
	    to: username, // list of receivers
	    subject: 'Thank you for registering, ' + fname + '!', // Subject line
	    text: 'Hello, ' + fname + '!',
	    html: '<p>Hello, <b>' + fname + htmlbody // html body
	};

	// send mail with defined transport object
	transporter.sendMail(mailOptions, function(err, info)
	{
	    if(err)
	        console.log(err);
	    else
	        console.log('Message sent: ' + info.response);
	});
}
exports.sendConfirmation = sendConfirmation